spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_mvc
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hilarydd7@gmail.com
    password: code
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
